web/demoapp/urls.py
from django.urls import path
from . import views

app_name = 'demoapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('celery/', views.celery_index, name='celery_index'),
    path('celery/random_add/', views.random_add, name='celery_random_add'),
    path('celery/random_mul/', views.random_mul, name='celery_random_mul'),
    path('celery/random_xsum/', views.random_xsum, name='celery_random_xsum'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('demoapp.urls')),
    path('admin/', admin.site.urls),
]

web/demoapp/models.py
from django.db import models

# Create your models here.

web/demoapp/views.py
import random
from django.shortcuts import render
from . import tasks


def index(request):
    context = {}
    return render(request, 'demoapp/index.html', context)


def celery_index(request):
    context = {}
    return render(request, 'demoapp/celery_index.html', context)


def random_add(request):
    a, b = random.choices(range(100), k=2)
    tasks.add.delay(a, b)
    context = {'function_detail': 'add({}, {})'.format(a, b)}
    return render(request, 'demoapp/celery_detail.html', context)


def random_mul(request):
    a, b = random.choices(range(100), k=2)
    tasks.mul.delay(a, b)
    context = {'function_detail': 'mul({}, {})'.format(a, b)}
    return render(request, 'demoapp/celery_detail.html', context)


def random_xsum(request):
    array = random.choices(range(100), k=random.randint(1, 10))
    tasks.xsum.delay(array)
    context = {'function_detail': 'xsum({})'.format(array)}
    return render(request, 'demoapp/celery_detail.html', context)

web/demoapp/templates/demoapp/celery_detail.html
<p>function <i>{{ function_detail }}</i> is executed by celery,</p>
<p>run "<i>docker-compose logs celery</i>" for detail.</p>

web/demoapp/templates/demoapp/celery_index.html
<ul>
    <li><a href="{% url 'demoapp:celery_random_add' %}">Celery Test: random add</a></li>
    <li><a href="{% url 'demoapp:celery_random_mul' %}">Celery Test: random mul</a></li>
    <li><a href="{% url 'demoapp:celery_random_xsum' %}">Celery Test: random xsum</a></li>
</ul>

web/demoapp/templates/demoapp/index.html
<h2>Django-Docker By huchenw</h2>
<ul>
  <li><a href="/celery/">Celery Test</a></li>
  <li><a href="/admin/">Django Admin</a></li>
</ul>